<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <!-- POM file generated with GWT webAppCreator -->
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.reactome.web.utils</groupId>
    <artifactId>analytics</artifactId>
    <version>2.1.4-SNAPSHOT</version>
    <packaging>jar</packaging>

    <parent>
        <groupId>org.reactome.maven</groupId>
        <artifactId>reactome-pwp-parent</artifactId>
        <version>1.0.3</version>
    </parent>

    <name>Analytics Helper</name>
    <description>Google Analytics helper</description>
    <url>https://github.com/reactome/pwp-analytics</url>

    <organization>
        <name>Reactome</name>
        <url>https://reactome.org</url>
    </organization>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>cqgong</id>
            <name>Chuqiao Gong</name>
            <email>cgong@ebi.ac.uk</email>
            <organization>The European Bioinformatics Institute</organization>
            <organizationUrl>https://www.ebi.ac.uk</organizationUrl>
        </developer>
        <developer>
            <id>EliotRagueneau</id>
            <name>EliotRagueneau</name>
            <email>eragueneau@ebi.ac.uk</email>
            <organization>The European Bioinformatics Institute</organization>
            <organizationUrl>https://www.ebi.ac.uk</organizationUrl>
        </developer>
        <developer>
            <id>gviteri</id>
            <name>Guilherme Viteri</name>
            <roles>
                <role>alumni</role>
            </roles>
            <organization>The European Bioinformatics Institute</organization>
            <organizationUrl>https://www.ebi.ac.uk/</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:git://github.com/reactome/pwp-analytics.git</connection>
        <developerConnection>scm:git:ssh://github.com/reactome/pwp-analytics.git</developerConnection>
        <url>https://github.com/reactome/pwp-analytics/tree/master</url>
    </scm>

    <properties>
        <!-- Convenience property to set the GWT version -->
        <gwtStyle>OBF</gwtStyle> <!-- OBF | PRETTY | DETAILED -->

        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <webappDirectory>${project.build.directory}/${project.build.finalName}</webappDirectory>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <appModule>org.reactome.web.utils.analytics.GoogleAnalytics</appModule>
        <appName>${appModule}</appName>

        <maven.gpg.version>3.2.7</maven.gpg.version>
        <maven.javadoc.version>3.11.2</maven.javadoc.version>
        <maven.release.version>3.3.1</maven.release.version>
        <nexus-staging-maven-plugin>1.7.0</nexus-staging-maven-plugin>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-user</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-codeserver</artifactId>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>jetty-webapp</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>jetty-servlets</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>jetty-annotations</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>apache-jsp</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.jetty.websocket</groupId>
                    <artifactId>websocket-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>apache-jsp</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-runner</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-servlet</artifactId>
        </dependency>

    </dependencies>

    <build>
        <!-- Generate compiled stuff in the folder used for developing mode -->
        <outputDirectory>${webappDirectory}/WEB-INF/classes</outputDirectory>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${maven.jar.version}</version>
            </plugin>
            <!-- GWT Maven Plugin -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <version>${gwtVersion}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>resources</goal>
                            <!-- Compile is not needed because other projects using the jar will do it -->
                            <!--<goal>compile</goal>-->
                            <goal>test</goal>
                            <goal>generateAsync</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>${maven.source.version}</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <extensions>true</extensions>
                <version>${maven.deploy.version}</version>
            </plugin>

            <!-- Nexus staging plugin for Sonatype deployment -->
            <plugin>
                <groupId>org.sonatype.plugins</groupId>
                <artifactId>nexus-staging-maven-plugin</artifactId>
                <version>${nexus-staging-maven-plugin}</version>
                <extensions>true</extensions>
                <configuration>
                    <serverId>ossrh</serverId>
                    <nexusUrl>https://s01.oss.sonatype.org/</nexusUrl>
                    <autoReleaseAfterClose>true</autoReleaseAfterClose>
                </configuration>
            </plugin>

            <!-- Generate JavaDoc jar file -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>${maven.javadoc.version}</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Signs deployed jar, source jar, and JavaDoc jar with GPG -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>${maven.gpg.version}</version>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <gpgExecutable>gpg</gpgExecutable> <!-- Explicitly specify the GPG executable -->
                </configuration>
            </plugin>

            <!-- Allows "release" mvn goal to deploy a SNAPSHOT or version release to Sonatype -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>${maven.release.version}</version>
                <configuration>
                    <remoteTagging>true</remoteTagging>
                    <autoVersionSubmodules>true</autoVersionSubmodules>
                    <useReleaseProfile>false</useReleaseProfile>
                    <releaseProfiles>release</releaseProfiles>
                    <goals>deploy</goals>
                </configuration>
            </plugin>

        </plugins>

        <!-- scp support for deployment (MVN 3) -->
        <extensions>
            <extension>
                <groupId>org.apache.maven.wagon</groupId>
                <artifactId>wagon-ssh</artifactId>
                <version>${wagon.ssh.version}</version>
            </extension>
        </extensions>
    </build>

    <pluginRepositories>
        <pluginRepository>
            <id>central</id>
            <name>Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
            <layout>default</layout>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <releases>
                <updatePolicy>never</updatePolicy>
            </releases>
        </pluginRepository>
    </pluginRepositories>

    <!-- Configures the distribution to nexus repository -->
    <distributionManagement>
        <!-- Sonatype Release repo -->
        <repository>
            <id>ossrh</id>
            <name>Sonatype Release Repository</name>
            <url>https://oss.sonatype.org/service/local/staging/deploy/maven2</url>
        </repository>

        <!-- Sonatype SNAPSHOT repo -->
        <snapshotRepository>
            <id>ossrh</id>
            <name>Sonatype Snapshot Repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
    </distributionManagement>

    <repositories>
        <!-- EBI repo -->
        <repository>
            <id>nexus-ebi-repo</id>
            <name>The EBI internal repository</name>
            <url>https://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <!-- EBI SNAPSHOT repo -->
        <repository>
            <id>nexus-ebi-snapshot-repo</id>
            <name>The EBI internal snapshot repository</name>
            <url>https://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>


</project>